twreporter/plate

- config.js
- models/Post.js
- models/Tag.js
- models/User.js
- remove the AutoCreate and add the some fields in the User and Post.
- add tag for the post
> fields modification in models

- .gitignore
- README.md
- config.sample.js
- keystone.js
- models/Image.js
- models/Tag.js
2. add Image and ImageCategory model
3. use GcsImage type
> 1. add gcs config

- models/Image.js
- package.json
> add resize image functionality

- models/Post.js
> add heroImage field

- models/Image.js
- models/Post.js
@hcchien 
could merge after this pr https://github.com/twreporter/keystone/pull/5 merged
> use imagerelationship field type for hero image

- models/Contact.js
- models/Post.js
- models/User.js
- merge the first name and last name to one field called 'name'
- add 'isFeatured' for the Post
- add byline for Post
> update the Post

- models/Audio.js
- models/Image.js
> Add Audio list type

- advanced.js
- express.js
- keystone.js
- models/Audio.js
- models/Company.js
- models/Contact.js
- models/Event.js
- models/FieldTest.js
- models/Gallery.js
- models/Image.js
- models/Job.js
- models/Post.js
- models/PostCategory.js
- models/Tag.js
- models/User.js
- package.json
- routes/index.js
just publish [our own keystone pkg ](https://www.npmjs.com/package/twreporter-keystone)
use this pkg as our lib.
> change keystone to twreporter-keystone

- package.json
> upgrade twreporter-keystone

- models/Post.js
use regex to test if heroImage is set or not.
@hcchien
> add heroImageSize field

- models/Image.js
> add tiny size image for resizing

- lib/extractIPTC.js
- lib/resizeImage.js
- models/Image.js
- models/ImageCollection.js
add models/ImageCollection.js, lib/extractIPTC.js and lib/resizeImage.js
@hcchien
> add models/ImageCollection.js, lib/extractIPTC.js and lib/resizeImage.js

- models/Audio.js
- models/Image.js
- models/ImageCollection.js
- make them be searchable by name
@hcchien
> Update models/Audio.js, models/Image.js and models/ImageCollection.js

- models/Audio.js
- models/Image.js
> Update models/Audio.js and models/Image.js

- models/Audio.js
> Update models/Audio.js, store description as draftjs obj

- models/Post.js
- models/Tag.js
Add a field in Post for topic, and it depends on the style. Setting the relationship to the Post with the style 'topic'.
> update the Post for the topic related

- models/Image.js
- models/ImageCollection.js
原來裁成 width 60 的 image ，放在 slideshow 裡面當 thumbnail 有點模糊，所以把寬改大一點。
@hcchien @garfieldduck
> Make tiny image bigger enough for being a thumbnail

- package.json
> Use pm2 and better-npm-run

- models/Post.js
> Add interactive style

- models/Post.js
This PR is based on [this pr](https://github.com/twreporter/keystone/pull/120)
> Add link to preview page

- models/Contact.js
- models/Topic.js
1.  [Update] Update models/Topic.js. More fields in the topic can be edited
2.  [Update] Update models/Contact.js. Track the changes
@garfieldduck
> [Updates] Update for topic landing page

- models/Contact.js
> [Update] Update relationship between contacts and posts

- .circleci/config.yml
- CHANGELOG.md
- package.json
In .circleci/config.yaml, use `npm install` instead of `yarn install`.
> Upgrade to 1.1.3

- CHANGELOG.md
- lib/resizeImage.js
- package.json
> Resize gif image

- CHANGELOG.md
- models/Post.js
- models/Theme.js
> Add Theme model and make it a field in the Post model

- CHANGELOG.md
- README.md
- models/Contact.js
- models/Post.js
- models/User.js
- package.json
- Add `secretEnabled` and `secretKey` to User
- Remove unexist default columns
- Update package name in README.md
> Add `secretEnabled` and `secretKey` to User model and fix some bugs

- models/Post.js
- `article:v2:default`
- `article:v2:pink`
- `article:v2:green`
- `article:v2:yellow`
> Add new article styles

- CHANGELOG.md
- models/Post.js
- heroImageSize: add `fullscreen` option
- style:
- remove `article`, `photography`, `article:fullscreen:dark` and `article:fullscreen:normal`
- add `article:v2:photo`
KanbanFlow card: https://kanbanflow.com/t/Cr7JJ9e8
>  models/Post.js modified

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- Dockerfile
- build-keystone-plugin.js
- keystone.js
- makefile
- package.json
- yarn.lock
> Move keystone-plugin from narwhale to keystone

- .circleci/config.yml
- keystone.js
- makefile
@YuCJ 
I merge this PR for further testing on release branch in advance.
If you have any concerns, please leave comments here.
> fix: fix socketio connection refuse problem

- .circleci/config.yml
- makefile
Merge this PR for testing.
If you have any concerns, please leave comments here.
> fix: specify socketio connection host and protocol along with port

- CHANGELOG.md
- package.json
- yarn.lock
This PR is to trigger CircleCI to build  and push docker image `keystone-plate@3.1.3`
> chore(release): 3.1.3

- build-config.js
- config-for-docker-build.js
https://github.com/twreporter/kubernetes-config/pull/17
https://github.com/twreporter/keystone/pull/153
> refactor: update config. `preview config` -> `preview origin`

- .circleci/config.yml
This patch adds slack orbs for notification and approval through the slack
channel.
> chore: add deployment after approval

- .circleci/config.yml
- CHANGELOG.md
- package.json
- yarn.lock
This PR triggers CircleCI to build 3.1.12 and deploy it on staging environment.
> chore: release 3.1.12 on staging environment

- CHANGELOG.md
- package.json
- yarn.lock
This PR triggers CircleCI to build v3.2.0 and deploy it on staging environment.
> chore: release v3.2.0 on staging

- yarn.lock
This reverts commit b2855deda235c158197179fad636a180ab1f7fca.
> Revert "chore: yarn-deduplicate"

- config-for-docker-build.js
- models/Audio.js
- models/Image.js
- models/Video.js
This PR updates gcs buckets according to https://github.com/twreporter/kubernetes-config/pull/26.
> Update gcs buckets 

- CHANGELOG.md
- package.json
- yarn.lock
This patch bumps the version to v3.2.5
> chore: bump version to v3.2.5

- build-config.js
- config-for-docker-build.js
This patch changes the session key to `keystone.sid` for better
identification.
> refactor: change session key to `keystone.sid`

- config-for-docker-build.js
- models/User.js
- package.json
- yarn.lock
Address [TWREPORTER-119](https://twreporter-org.atlassian.net/browse/TWREPORTER-119).
https://github.com/twreporter/keystone/pull/202 is required by this change.
> feat: add avatar to user model

- models/Tag.js
After discussion with PM, we need to adjust the label wording of `latest_order`.
> fix: `latest_order` label wording

- package.json
- yarn.lock
- @twreporter/keystone: v0.9.10-rc.2
> chore: update @twreporter package

- package.json
- yarn.lock
> feat: update keystone to v0.9.10

- CHANGELOG.md
- package.json
> chore: bump version v3.2.18

- CHANGELOG.md
- package.json
- yarn.lock
> chore: release v3.2.18 to staging

- CHANGELOG.md
- package.json
- yarn.lock
[[資訊架構] 新增「基金會消息」主分類-keystone
](https://app.asana.com/0/1203699264568808/1205988685100796/f)
> chore: bump version to v3.2.19-rc.0

- CHANGELOG.md
- models/Post.js
- package.json
[[維運] 清除資訊架構新舊相容的 code](https://app.asana.com/0/1203699264568808/1206398708372264/f)
> feat: set categories to noedit

- CHANGELOG.md
- models/Post.js
- package.json
- yarn.lock
> chore: test v3.2.20-rc.0 on staging

- CHANGELOG.md
- package.json
> chore: bump version to v3.2.20

- CHANGELOG.md
- models/Post.js
- package.json
> chore: test v3.2.20 on staging

- models/Post.js
- package.json
- yarn.lock
fix defects in [[會員制]重要報導回顧-CMS](https://app.asana.com/0/1203699264568808/1206721264374714/f)
https://github.com/twreporter/keystone/pull/246
> fix: add `maxLength` for `reviewWord` field

- models/Post.js
[[維運] 重要報導回顧說明字數增加](https://app.asana.com/0/1202936421725081/1207491592237033/f)
N/A
> fix: update max length of Post.reviewWord

- models/Post.js
- package.json
- yarn.lock
[[維運] 文章頁新增版型：滿版版型-CMS
](https://app.asana.com/0/1203699264568808/1207629974038928/f)
- also add `article:v2:embede` options for styles
https://github.com/twreporter/keystone/pull/252
> feat: add `leading_embeded` field for Post

- CHANGELOG.md
- models/Post.js
- package.json
- yarn.lock
> fix: embeded typo

- CHANGELOG.md
- models/Post.js
- package.json
- yarn.lock
> chore: test v3.2.25-rc.0 on staging

- models/PostFollowup.js
[[維運] 修改報導追蹤下拉選項的排序](https://app.asana.com/0/1203699264568808/1208604769542493/f)
N/A
> fix: update `PostFollowups` list sorting
